package webrobot;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CamisRobotTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void camisRobotTest() {
    // Test name: CamisRobotTest
    // Step # | name | target | value
    // 1 | open | /educaciontrendi/yxbdm3vsnd8t7xnq | 
    driver.get("https://padlet.com/educaciontrendi/yxbdm3vsnd8t7xnq");
    // 2 | setWindowSize | 550x691 | 
    driver.manage().window().setSize(new Dimension(550, 691));
    // 3 | runScript | window.scrollTo(0,0) | 
    js.executeScript("window.scrollTo(0,0)");
    // 4 | click | css=#wish-2309587956 .bg-light-ui-100 > .pt-2 .oricon | 
    driver.findElement(By.cssSelector("#wish-2309587956 .bg-light-ui-100 > .pt-2 .oricon")).click();
    // 5 | click | css=.oricon:nth-child(5) | 
    driver.findElement(By.cssSelector(".oricon:nth-child(5)")).click();
  }
}
